version: '3'

services:
  redis:
    image: "redis:alpine"

  celery:
    restart: always
    image: bank:1.1
    command: celery -A banc worker -l info
    depends_on:
      - redis

  celery-beat: 
    image: bank:1.1
    command: celery -A banc beat -l info
    depends_on:
      - redis