version: '3'

services:

  db_prod:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
    volumes:
      - ./volumes/postgresql/pg-data1:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  db_dev:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - POSTGRES_DB=${POSTGRES_DB_DEV}
    volumes:
      - ./volumes/postgresql/pg-data2:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  web:
    build: 
      context: .
    command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    restart: always
    ports:
      - "8091:8080"
    depends_on:
      - redis
      - db_prod

  redis:
    image: "redis:alpine"

  celery:
    restart: always
    build: 
      context: .
    command: celery -A banc worker -l info
    depends_on:
      - redis

  celery-beat: 
    build: 
      context: .
    command: celery -A banc beat -l info
    depends_on:
      - redis