# Generated by Django 4.0.6 on 2022-07-19 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.enum_field
import mainapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('balance_action', helpers.enum_field.EnumField(default=mainapp.models.Action.BalanceAction['CREATED'], enum={'names': {'CREATED': 'Created', 'DEPOSITED': 'Deposited', 'WITHDRAWNED': 'Withdrawned'}, 'value': 'BalanceAction'})),
                ('payment_type', helpers.enum_field.EnumField(default=mainapp.models.Action.PaymentType['NONE'], enum={'names': {'CASH': 'Cash', 'NONE': 'None', 'TRANSFER': 'Transfer'}, 'value': 'PaymentType'})),
                ('delta', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.account')),
            ],
        ),
    ]
