# Generated by Django 4.0.6 on 2022-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_action_account_from_alter_action_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
