# Generated by Django 4.0.6 on 2022-07-26 19:04

from django.db import migrations
import helpers.enum_field
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_action_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='balance_action',
            field=helpers.enum_field.EnumField(default=mainapp.models.Action.BalanceAction['CREATED'], enum={'names': {'CREATED': 'Created', 'DEPOSITED': 'Deposited', 'UPDATED': 'Updated', 'WITHDRAWNED': 'Withdrawned'}, 'value': 'BalanceAction'}),
        ),
    ]
