# Generated by Django 4.0.6 on 2022-07-30 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_action_balance_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.account')),
            ],
        ),
    ]
