# Generated by Django 4.0.6 on 2022-08-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_aggregates'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregates',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-02T16:24:50'),
            preserve_default=False,
        ),
    ]
